language: cpp

compiler:
- clang

os:
- osx

before_install:
- if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then make -f Makefile.macos travis_install; fi
- pwd
- cd /Users/travis/build/mull-project/mull

# Uncomment this line when support Rust
# - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then curl -sf https://static.rust-lang.org/rustup.sh | sudo sh; fi

# Build steps
script:
- if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then make -f Makefile.macos travis; fi

