language: cpp
compiler: clang
sudo: required

os:
- linux
- osx

dist: xenial

env:
- LLVM_VERSION=3.9
- LLVM_VERSION=4.0
- LLVM_VERSION=5.0
- LLVM_VERSION=6.0
- LLVM_VERSION=7.0

before_install:
- echo $PLAYBOOK
- if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then HOMEBREW_NO_AUTO_UPDATE=1 brew install ansible; fi
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo pip install ansible; fi
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get update; fi

# Build steps
script:
- if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then cd infrastructure && ansible-playbook macos-playbook.yaml -e llvm_version=$LLVM_VERSION.0 -e source_dir=$PWD/.. -e gitref=$TRAVIS_COMMIT -e host=localhost --verbose; fi
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then cd infrastructure && ansible-playbook ubuntu-playbook.yaml -e llvm_version=$LLVM_VERSION.0 -e source_dir=$PWD/.. -e gitref=$TRAVIS_COMMIT -e host=localhost --verbose; fi

