language: cpp

compiler:
- clang

os:
- osx

before_install:
- if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then brew update; fi
- if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then brew upgrade cmake; fi
- if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then brew install llvm@3.9; fi
- if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then brew install zlib; fi
- if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then brew install ncurses; fi
- if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then brew install sqlite; fi
- if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then brew install ninja; fi

# Uncomment this line when support Rust
# - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then curl -sf https://static.rust-lang.org/rustup.sh | sudo sh; fi

install:
- cd googletest
- make install
- cd ..

# Build steps
script:
- make test_unit