## Required parameters.
project_name: test-objc
bitcode_file_list: /opt/mull/objc.bitcode.list

## Optional parameters.
# fork: false
# dry_run: false
# test_framework: GoogleTest
# diagnostics: none # none/survived/killed/all

## Mutation Operators.
## You can enable any of the following, the parsing is inclusive.
## If mutation_operators is missing altogether Mull defaults to 'default' group.
mutators:
# - default        #
# - math         # Consists of math_*_mutation_operator (4 math mutation operators).
# - conditional  # negate_mutation_operator + and_or_replacement_mutation_operator.
# - functions    # remove_void_function_mutation_operator + replace_call_mutation_operator
# - all          # enables all available mutation operators.
# - experimental # enables experimental mutation operators.
#
## Or single mutation operators:
# Mathematical.
- math_add_mutator
# - math_mul_mutator
# - math_sub_mutator
# - math_div_mutator
# Conditional
# - negate_mutator
# - and_or_replacement_mutation_operator
# Functions
# - remove_void_function_mutation_operator
# - replace_call_mutation_operator
# Constants
- scalar_value_mutator
