[package]

name = "example"
version = "0.0.1"
authors = [ "Stanislav Pankevich <s.pankevich@gmail.com>" ]

[lib]
name = "example"
path = "example.rs"
test = true
doctest = false

[dev-dependencies]
# tempdir = "*"

